logLevel = "DEBUG"
[entryPoints]
  [entryPoints.http]
        address = ":80"
        [entryPoints.http.redirect]
                entryPoint = "https"
  [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]
defaultEntryPoints = ["http", "https"]

#Lets Encrypt
[acme]
email = "joe@acmecorp.com"
storage = "/letsencrypt/acme.json"
entryPoint = "https"
OnHostRule = true
[[acme.domains]]
   main = "cosmic.acmecorp.com"

#Web UI
[web]
address = ":8080"
ReadOnly = true
 [web.statistics]
   RecentErrors = 10
   [web.auth.basic]
     users = ["joe:$apr1$secure4youp71"]

#docker backend
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "acmecorp.com"
watch = true
exposedbydefault = true

